global:
  customSecretName: newrelic-infra-secrets-v1
  customSecretKey: NRIA_LICENSE_KEY
  # clusterName: 

resources:
  limits:
    cpu: 125m
    memory: 128Mi
  requests:
    cpu: 60m
    memory: 64Mi
